
on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: magics-python
    - name: checkout test
      uses: actions/checkout@v2
      with: 
        repository: ecmwf/magics-test
        path: magics-test
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ecmwflibs pytest wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Running full test suite
      run: |
        echo $GITHUB_WORKSPACE/magics-python
        cd $GITHUB_WORKSPACE/magics-python
        pip install .
        echo $GITHUB_WORKSPACE/magics-test
        ls $MAGICS_PYTHON_TESTS
        cd $GITHUB_WORKSPACE/magics-test
        pytest 
      env:
        MAGICS_PYTHON_TESTS: ${{ GITHUB_WORKSPACE }}/magics-test/test/gallery
      
