
on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: magics-python
    - name: checkout test
      uses: actions/checkout@v2
      with: 
        repository: ecmwf/magics-test
        path: magics-test
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ecmwflibs pytest 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pip install magics-python
        cd magics-test
        pytest 
